CREATE TABLE orders (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number VARCHAR(255) UNIQUE NOT NULL,
    user_id UUID NOT NULL REFERENCES auth(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'NEW',
    accrual INT DEFAULT 0,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
